name: Ruchika Juneja, The Impossible Dream
title: Ruchika Juneja, The Impossible Dream
baseurl: "/blog"
url: "http://ruchikajuneja.com"
markdown: kramdown
theme: jekyll-theme-cayman
exclude: [vendor]
